
# C++ project
language: cpp

# Only build master and tags
if: branch = master OR tag IS present

git:
    submodules: true

env:
  global:
    - BINTRAY_USER=manromen
    # BINTRAY_KEY
    - secure: "cmzzkhlpQT1e+9rfWttApomNnjpZxKiP+5zoSxihiVC1w/6htKvWwlzQyXzGe8Bwr0y0qBolIfMZYABDB4W6dottP51AVEO/RYDMdWdlvz1ztfnveCsaadaRK8AD6riRNfY7S8JLStX8MaGm6ZmR9b7fQpkoK5sZORdSWcQTEnMhcRrK5A5hQ6ljCG+rjhoisjBgeCsLijJ2JoeQqbq88XE/gddQij7a6XjZtY175sJLzwPopS5mQOU4sF5IRUrR3xYJQ2R53bYyanpOdVe3/Bj0BSAfBs6Lqnsh5RrBqImRjHmYKsQHwZP2Eqm58sXy9cO3InP8A9RxBZp5Pwd/+JaOxJ8DLhnSK6t+Jz2ux3NPe8wuDlUALRZi351MtxTub8pPcPRx0pVm/mFtMivhjf7QpEGsMsb5S2ZfAYIN87RihUpqKd2LfivdgHav416JKBVB9eG0pRCZETu4qO+bTsHN+glAYzjbtWZW/bRqsw0G1AYaiAuQzup76QVPcfHBzQnaMLCXAolD9JFG2JgVOz2tJLK8sAsfJAmOk5bzvG1L0yeFXbFkZGfQM2m06GQ3NXv1Wpy7nXl4voJMwiOS5tF84dxb+dtJXvU6JK0ecOZBKS9xJlLHOpT5cqtYBeZuEKuM/hImPe/3YYgCwDOZYJCSR10bBF07NdOsnSVy3ss="
    - CONAN_REPOSITORY=https://api.bintray.com/conan/manromen/rgpaul
    - CONAN_REPOSITORY_NAME=rgpaul
    - CONAN_USER=rgpaul
    - CONAN_CHANNEL=stable
    - CONAN_PACKAGE_NAME=godot-cpp
    - CONAN_LIBRARY_VERSION=20190816

### before installing deps
before_install:
  # Download Android NDK from Google
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TARGET_PLATFORM" == "android" ]]; then
      curl -sSOL "https://dl.google.com/android/repository/android-ndk-${TRAVIS_ANDROID_NDK_VERSION}-linux-x86_64.zip";
      unzip -q -o android-ndk-${TRAVIS_ANDROID_NDK_VERSION}-linux-x86_64.zip;
      export ANDROID_NDK_PATH=${TRAVIS_BUILD_DIR}/android-ndk-${TRAVIS_ANDROID_NDK_VERSION};
    fi

### install deps
install:

  # Install python and conan for windows
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install python3;
      choco install conan;
    fi

  # Install conan (linux) - python3 -m pip3 install conan --user; => no module named pip3 ?
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install conan --user;
    fi

  # Install conan (macos)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip3 install conan;
    fi

  # Add conan repository and apply conan config
  - conan remote add ${CONAN_REPOSITORY_NAME} ${CONAN_REPOSITORY}
  - conan config install ${TRAVIS_BUILD_DIR}/.travis/conan/config.zip

  # login to conan
  - conan user -p "$BINTRAY_KEY" -r ${CONAN_REPOSITORY_NAME} ${BINTRAY_USER}

### build script
script:
  # show OS/compiler version
  - uname -a

  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # Android Builds
  - if [ "$TARGET_PLATFORM" == "android" ]; then
      conan create . ${CONAN_PACKAGE_NAME}/${CONAN_LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=Android -s os.api_level=${TRAVIS_ANDROID_API_LEVEL} -s compiler=${TRAVIS_ANDROID_COMPILER} -s compiler.version=${TRAVIS_ANDROID_COMPILER_VERSION} -s compiler.libcxx=${TRAVIS_ANDROID_COMPILER_LIBCXX} -s build_type=${TARGET_BUILD_TYPE} -o android_ndk=${TRAVIS_ANDROID_NDK_VERSION} -o android_stl_type=${TRAVIS_ANDROID_STL_TYPE} -s arch=${TRAVIS_ANDROID_ARCH} -o shared=False;
    fi

  # macOS Builds
  - if [ "$TARGET_PLATFORM" == "macos" ]; then
      export MACOS_SDK_VERSION=$(xcodebuild -showsdks | grep macosx | awk '{print $4}' | sed 's/[^0-9,\.]*//g');
      echo "macOS SDK ${MACOS_SDK_VERSION}";
      conan create . ${CONAN_PACKAGE_NAME}/${CONAN_LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=Macos -s os.version=${MACOS_SDK_VERSION} -s arch=${TARGET_ARCH} -s build_type=${TARGET_BUILD_TYPE} -o shared=False;
    fi

  # iOS Builds
  - if [ "$TARGET_PLATFORM" == "ios" ]; then
      export IOS_SDK_VERSION=$(xcodebuild -showsdks | grep iphoneos | awk '{print $4}' | sed 's/[^0-9,\.]*//g');
      echo "iOS SDK ${IOS_SDK_VERSION}";
      conan create . ${CONAN_PACKAGE_NAME}/${CONAN_LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=iOS -s os.version=${IOS_SDK_VERSION} -s arch=${TARGET_ARCH} -s build_type=${TARGET_BUILD_TYPE} -o shared=False;
    fi

  # Windows Builds
  - if [ "$TARGET_PLATFORM" == "windows" ]; then
      conan create . ${CONAN_PACKAGE_NAME}/${LIBRARY_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} -s os=Windows -s compiler="Visual Studio" -s compiler.runtime=MT -s arch=${TARGET_ARCH} -s build_type=${TARGET_BUILD_TYPE} -o shared=False;
    fi

deploy:
  provider: script
  script: bash .travis/conan-deploy.sh
  on:
    tags: true

### build matrix
matrix:
  include:

    ### Android NDK r20 - arm64-v8a ###
    - os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r20
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=armv8
        - TRAVIS_ANDROID_API_LEVEL=21
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5', 'python3-pip']

    ### Android NDK r20 - armeabi-v7a ###
    - os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r20
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=armv7
        - TRAVIS_ANDROID_API_LEVEL=19
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5', 'python3-pip']

    ### Android NDK r20 - x86 ###
    - os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r20
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=x86
        - TRAVIS_ANDROID_API_LEVEL=19
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5', 'python3-pip']

    ### Android NDK r20 - x86_64 ###
    - os: linux
      dist: xenial # Ubuntu 16.04 (Xenial)
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r20
        - TRAVIS_ANDROID_COMPILER=clang
        - TRAVIS_ANDROID_COMPILER_VERSION=8.0
        - TRAVIS_ANDROID_ARCH=x86_64
        - TRAVIS_ANDROID_API_LEVEL=21
        - TRAVIS_ANDROID_COMPILER_LIBCXX=libc++
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - TARGET_BUILD_TYPE=Release
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5', 'python3-pip']
      
    # iOS - Release
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=ios
        - TARGET_ARCH=armv8
        - TARGET_BUILD_TYPE=Release

    # iOS - Debug
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=ios
        - TARGET_ARCH=armv8
        - TARGET_BUILD_TYPE=Debug

    # iOS - Simulator
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=ios
        - TARGET_ARCH=x86_64
        - TARGET_BUILD_TYPE=Debug

    # macOS - Release
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=macos
        - TARGET_ARCH=x86_64
        - TARGET_BUILD_TYPE=Release

    # macOS - Debug
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env:
        - TARGET_PLATFORM=macos
        - TARGET_ARCH=x86_64
        - TARGET_BUILD_TYPE=Debug

